/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISmartRouter } from './ISmartRouter.js';
export type { RouterFactory } from './RouterFactory.js';