/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface RouterFactoryInterface extends Interface {
    getFunction(nameOrSignature: "acceptOwnership" | "deployRouter" | "getUserRouters" | "getVault" | "owner" | "pendingOwner" | "routerImplementation" | "tokenToVault" | "transferOwnership" | "updateImplementation" | "userRouters" | "whitelistVault"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ImplementationUpdated" | "OwnershipTransferStarted" | "OwnershipTransferred" | "RouterDeployed" | "VaultWhitelisted"): EventFragment;

    encodeFunctionData(functionFragment: 'acceptOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'deployRouter', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getUserRouters', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getVault', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingOwner', values?: undefined): string;
encodeFunctionData(functionFragment: 'routerImplementation', values?: undefined): string;
encodeFunctionData(functionFragment: 'tokenToVault', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateImplementation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'userRouters', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'whitelistVault', values: [AddressLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'acceptOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deployRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserRouters', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'routerImplementation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenToVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateImplementation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userRouters', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'whitelistVault', data: BytesLike): Result;
  }

  
    export namespace ImplementationUpdatedEvent {
      export type InputTuple = [oldImpl: AddressLike, newImpl: AddressLike];
      export type OutputTuple = [oldImpl: string, newImpl: string];
      export interface OutputObject {oldImpl: string, newImpl: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferStartedEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RouterDeployedEvent {
      export type InputTuple = [owner: AddressLike, router: AddressLike];
      export type OutputTuple = [owner: string, router: string];
      export interface OutputObject {owner: string, router: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VaultWhitelistedEvent {
      export type InputTuple = [token: AddressLike, vault: AddressLike];
      export type OutputTuple = [token: string, vault: string];
      export interface OutputObject {token: string, vault: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RouterFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): RouterFactory;
    waitForDeployment(): Promise<this>;

    interface: RouterFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    acceptOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    deployRouter: TypedContractMethod<
      [operatingPct: BigNumberish, treasuryPct: BigNumberish, lockedPct: BigNumberish, allowanceAmount: BigNumberish, allowancePeriod: BigNumberish, ],
      [string],
      'nonpayable'
    >
    

    
    getUserRouters: TypedContractMethod<
      [user: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    getVault: TypedContractMethod<
      [token: AddressLike, ],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pendingOwner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    routerImplementation: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    tokenToVault: TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateImplementation: TypedContractMethod<
      [newImplementation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    userRouters: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    whitelistVault: TypedContractMethod<
      [token: AddressLike, vault: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'acceptOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deployRouter'): TypedContractMethod<
      [operatingPct: BigNumberish, treasuryPct: BigNumberish, lockedPct: BigNumberish, allowanceAmount: BigNumberish, allowancePeriod: BigNumberish, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getUserRouters'): TypedContractMethod<
      [user: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getVault'): TypedContractMethod<
      [token: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pendingOwner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'routerImplementation'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'tokenToVault'): TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateImplementation'): TypedContractMethod<
      [newImplementation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'userRouters'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'whitelistVault'): TypedContractMethod<
      [token: AddressLike, vault: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ImplementationUpdated'): TypedContractEvent<ImplementationUpdatedEvent.InputTuple, ImplementationUpdatedEvent.OutputTuple, ImplementationUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferStarted'): TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'RouterDeployed'): TypedContractEvent<RouterDeployedEvent.InputTuple, RouterDeployedEvent.OutputTuple, RouterDeployedEvent.OutputObject>;
getEvent(key: 'VaultWhitelisted'): TypedContractEvent<VaultWhitelistedEvent.InputTuple, VaultWhitelistedEvent.OutputTuple, VaultWhitelistedEvent.OutputObject>;

    filters: {
      
      'ImplementationUpdated(address,address)': TypedContractEvent<ImplementationUpdatedEvent.InputTuple, ImplementationUpdatedEvent.OutputTuple, ImplementationUpdatedEvent.OutputObject>;
      ImplementationUpdated: TypedContractEvent<ImplementationUpdatedEvent.InputTuple, ImplementationUpdatedEvent.OutputTuple, ImplementationUpdatedEvent.OutputObject>;
    

      'OwnershipTransferStarted(address,address)': TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
      OwnershipTransferStarted: TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'RouterDeployed(address,address)': TypedContractEvent<RouterDeployedEvent.InputTuple, RouterDeployedEvent.OutputTuple, RouterDeployedEvent.OutputObject>;
      RouterDeployed: TypedContractEvent<RouterDeployedEvent.InputTuple, RouterDeployedEvent.OutputTuple, RouterDeployedEvent.OutputObject>;
    

      'VaultWhitelisted(address,address)': TypedContractEvent<VaultWhitelistedEvent.InputTuple, VaultWhitelistedEvent.OutputTuple, VaultWhitelistedEvent.OutputObject>;
      VaultWhitelisted: TypedContractEvent<VaultWhitelistedEvent.InputTuple, VaultWhitelistedEvent.OutputTuple, VaultWhitelistedEvent.OutputObject>;
    
    };
  }