/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface SocialJackpotInterface extends Interface {
    getFunction(nameOrSignature: "PLATFORM_FEE_BPS" | "createRoom" | "enterRoom" | "feeRecipient" | "getParticipantInfo" | "nextRoomId" | "participants" | "roomParticipants" | "rooms" | "vote"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PlatformFeePaid" | "RoomCreated" | "RoomResolved" | "UserEntered" | "Voted" | "VotingStarted"): EventFragment;

    encodeFunctionData(functionFragment: 'PLATFORM_FEE_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'createRoom', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'enterRoom', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'feeRecipient', values?: undefined): string;
encodeFunctionData(functionFragment: 'getParticipantInfo', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'nextRoomId', values?: undefined): string;
encodeFunctionData(functionFragment: 'participants', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'roomParticipants', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'rooms', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'PLATFORM_FEE_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createRoom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'enterRoom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getParticipantInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextRoomId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'participants', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'roomParticipants', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rooms', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
  }

  
    export namespace PlatformFeePaidEvent {
      export type InputTuple = [roomId: BigNumberish, recipient: AddressLike, amount: BigNumberish];
      export type OutputTuple = [roomId: bigint, recipient: string, amount: bigint];
      export interface OutputObject {roomId: bigint, recipient: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoomCreatedEvent {
      export type InputTuple = [roomId: BigNumberish, creator: AddressLike, token: AddressLike, entryFee: BigNumberish, maxParticipants: BigNumberish, numWinners: BigNumberish];
      export type OutputTuple = [roomId: bigint, creator: string, token: string, entryFee: bigint, maxParticipants: bigint, numWinners: bigint];
      export interface OutputObject {roomId: bigint, creator: string, token: string, entryFee: bigint, maxParticipants: bigint, numWinners: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoomResolvedEvent {
      export type InputTuple = [roomId: BigNumberish, winners: AddressLike[], payoutPerWinner: BigNumberish];
      export type OutputTuple = [roomId: bigint, winners: string[], payoutPerWinner: bigint];
      export interface OutputObject {roomId: bigint, winners: string[], payoutPerWinner: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UserEnteredEvent {
      export type InputTuple = [roomId: BigNumberish, user: AddressLike, pitch: string];
      export type OutputTuple = [roomId: bigint, user: string, pitch: string];
      export interface OutputObject {roomId: bigint, user: string, pitch: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VotedEvent {
      export type InputTuple = [roomId: BigNumberish, voter: AddressLike, candidate: AddressLike];
      export type OutputTuple = [roomId: bigint, voter: string, candidate: string];
      export interface OutputObject {roomId: bigint, voter: string, candidate: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VotingStartedEvent {
      export type InputTuple = [roomId: BigNumberish];
      export type OutputTuple = [roomId: bigint];
      export interface OutputObject {roomId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SocialJackpot extends BaseContract {
    
    connect(runner?: ContractRunner | null): SocialJackpot;
    waitForDeployment(): Promise<this>;

    interface: SocialJackpotInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    PLATFORM_FEE_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    createRoom: TypedContractMethod<
      [_token: AddressLike, _entryFee: BigNumberish, _maxParticipants: BigNumberish, _numWinners: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    enterRoom: TypedContractMethod<
      [roomId: BigNumberish, pitch: string, ],
      [void],
      'nonpayable'
    >
    

    
    feeRecipient: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getParticipantInfo: TypedContractMethod<
      [roomId: BigNumberish, user: AddressLike, ],
      [[string, bigint, boolean] & {pitch: string, votesReceived: bigint, hasVoted: boolean }],
      'view'
    >
    

    
    nextRoomId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    participants: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [[string, string, bigint, boolean, boolean] & {addr: string, pitch: string, votesReceived: bigint, hasVoted: boolean, exists: boolean }],
      'view'
    >
    

    
    roomParticipants: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    rooms: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, bigint] & {id: bigint, creator: string, token: string, entryFee: bigint, maxParticipants: bigint, numWinners: bigint, state: bigint, totalVotesCast: bigint }],
      'view'
    >
    

    
    vote: TypedContractMethod<
      [roomId: BigNumberish, candidate: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'PLATFORM_FEE_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createRoom'): TypedContractMethod<
      [_token: AddressLike, _entryFee: BigNumberish, _maxParticipants: BigNumberish, _numWinners: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'enterRoom'): TypedContractMethod<
      [roomId: BigNumberish, pitch: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'feeRecipient'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getParticipantInfo'): TypedContractMethod<
      [roomId: BigNumberish, user: AddressLike, ],
      [[string, bigint, boolean] & {pitch: string, votesReceived: bigint, hasVoted: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'nextRoomId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'participants'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [[string, string, bigint, boolean, boolean] & {addr: string, pitch: string, votesReceived: bigint, hasVoted: boolean, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'roomParticipants'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'rooms'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, bigint] & {id: bigint, creator: string, token: string, entryFee: bigint, maxParticipants: bigint, numWinners: bigint, state: bigint, totalVotesCast: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [roomId: BigNumberish, candidate: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'PlatformFeePaid'): TypedContractEvent<PlatformFeePaidEvent.InputTuple, PlatformFeePaidEvent.OutputTuple, PlatformFeePaidEvent.OutputObject>;
getEvent(key: 'RoomCreated'): TypedContractEvent<RoomCreatedEvent.InputTuple, RoomCreatedEvent.OutputTuple, RoomCreatedEvent.OutputObject>;
getEvent(key: 'RoomResolved'): TypedContractEvent<RoomResolvedEvent.InputTuple, RoomResolvedEvent.OutputTuple, RoomResolvedEvent.OutputObject>;
getEvent(key: 'UserEntered'): TypedContractEvent<UserEnteredEvent.InputTuple, UserEnteredEvent.OutputTuple, UserEnteredEvent.OutputObject>;
getEvent(key: 'Voted'): TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
getEvent(key: 'VotingStarted'): TypedContractEvent<VotingStartedEvent.InputTuple, VotingStartedEvent.OutputTuple, VotingStartedEvent.OutputObject>;

    filters: {
      
      'PlatformFeePaid(uint256,address,uint256)': TypedContractEvent<PlatformFeePaidEvent.InputTuple, PlatformFeePaidEvent.OutputTuple, PlatformFeePaidEvent.OutputObject>;
      PlatformFeePaid: TypedContractEvent<PlatformFeePaidEvent.InputTuple, PlatformFeePaidEvent.OutputTuple, PlatformFeePaidEvent.OutputObject>;
    

      'RoomCreated(uint256,address,address,uint256,uint256,uint256)': TypedContractEvent<RoomCreatedEvent.InputTuple, RoomCreatedEvent.OutputTuple, RoomCreatedEvent.OutputObject>;
      RoomCreated: TypedContractEvent<RoomCreatedEvent.InputTuple, RoomCreatedEvent.OutputTuple, RoomCreatedEvent.OutputObject>;
    

      'RoomResolved(uint256,address[],uint256)': TypedContractEvent<RoomResolvedEvent.InputTuple, RoomResolvedEvent.OutputTuple, RoomResolvedEvent.OutputObject>;
      RoomResolved: TypedContractEvent<RoomResolvedEvent.InputTuple, RoomResolvedEvent.OutputTuple, RoomResolvedEvent.OutputObject>;
    

      'UserEntered(uint256,address,string)': TypedContractEvent<UserEnteredEvent.InputTuple, UserEnteredEvent.OutputTuple, UserEnteredEvent.OutputObject>;
      UserEntered: TypedContractEvent<UserEnteredEvent.InputTuple, UserEnteredEvent.OutputTuple, UserEnteredEvent.OutputObject>;
    

      'Voted(uint256,address,address)': TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
      Voted: TypedContractEvent<VotedEvent.InputTuple, VotedEvent.OutputTuple, VotedEvent.OutputObject>;
    

      'VotingStarted(uint256)': TypedContractEvent<VotingStartedEvent.InputTuple, VotingStartedEvent.OutputTuple, VotingStartedEvent.OutputObject>;
      VotingStarted: TypedContractEvent<VotingStartedEvent.InputTuple, VotingStartedEvent.OutputTuple, VotingStartedEvent.OutputObject>;
    
    };
  }