// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Dummy$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Dummy";
  readonly sourceName: "contracts/mocks/Dummy.sol";
  readonly abi: [{"inputs":[],"name":"token","outputs":[{"internalType":"contract IERC20","name":"","type":"address"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x6080604052348015600e575f5ffd5b50608d80601a5f395ff3fe6080604052348015600e575f5ffd5b50600436106026575f3560e01c8063fc0c546a14602a575b5f5ffd5b5f54603b906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f3fea264697066735822122098647617ed78ceffc6b1e6731a84b852862e6b48b4838a493e57f7caa5d0cdcf64736f6c63430008230033";
  readonly deployedBytecode: "0x6080604052348015600e575f5ffd5b50600436106026575f3560e01c8063fc0c546a14602a575b5f5ffd5b5f54603b906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f3fea264697066735822122098647617ed78ceffc6b1e6731a84b852862e6b48b4838a493e57f7caa5d0cdcf64736f6c63430008230033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/mocks/Dummy.sol";
  readonly buildInfoId: "solc-0_8_28-a2e991842350573f69721695229cffb6650093fe";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Dummy"]: Dummy$Type;
    ["contracts/mocks/Dummy.sol:Dummy"]: Dummy$Type;
  }
}