export const routerFactoryAbi = [
  "function owner() view returns (address)",
  "function pendingOwner() view returns (address)",
  "function routerImplementation() view returns (address)",
  "function tokenToVault(address) view returns (address)",
  "function getVault(address token) view returns (address)",
  "function deployRouter(uint256 operatingPct,uint256 treasuryPct,uint256 lockedPct,uint256 allowanceAmount,uint256 allowancePeriod) returns (address)",
  "function getUserRouters(address user) view returns (address[])",
  "function transferOwnership(address newOwner)",
  "function acceptOwnership()",
  "function updateImplementation(address newImplementation)",
  "event VaultWhitelisted(address indexed token,address indexed vault)",
  "event RouterDeployed(address indexed owner,address indexed router)",
  "event OwnershipTransferStarted(address indexed previousOwner,address indexed newOwner)",
  "event OwnershipTransferred(address indexed previousOwner,address indexed newOwner)",
  "event ImplementationUpdated(address indexed oldImpl,address indexed newImpl)",
] as const;

export const smartRouterAbi = [
  "function owner() view returns (address)",
  "function pendingOwner() view returns (address)",
  "function factory() view returns (address)",
  "function operatingPct() view returns (uint256)",
  "function treasuryPct() view returns (uint256)",
  "function lockedPct() view returns (uint256)",
  "function allowanceAmount() view returns (uint256)",
  "function allowancePeriod() view returns (uint256)",
  "function lastAllowanceRelease() view returns (uint256)",
  "function treasuryShares() view returns (uint256)",
  "function lockedShares() view returns (uint256)",
  "function savePct() view returns (uint256)",
  "function savedPrincipal() view returns (uint256)",
  "function savedShares() view returns (uint256)",
  "function initialize(address _owner,address _factory,uint256 _operatingPct,uint256 _treasuryPct,uint256 _lockedPct,uint256 _allowanceAmount,uint256 _allowancePeriod)",
  "function processPayment(address token)",
  "function claimAllowance(address token)",
  "function withdrawTreasury(address token,uint256 amount)",
  "function updateSettings(uint256 _operatingPct,uint256 _treasuryPct,uint256 _lockedPct,uint256 _allowanceAmount,uint256 _allowancePeriod)",
  "function updateSavePct(uint256 _savePct)",
  "function payAndSave(address token,address recipient,uint256 amount)",
  "function withdrawSavings(address token,uint256 amount)",
  "function getSavingsValue(address token) view returns (uint256 principal,uint256 totalValue,uint256 yieldEarned)",
  "function getTreasuryValue(address token) view returns (uint256)",
  "function getLockedValue(address token) view returns (uint256)",
  "function transferOwnership(address newOwner)",
  "function acceptOwnership()",
  "function emergencyWithdraw(address token)",
  "event PaymentProcessed(address indexed token,uint256 totalAmount,uint256 operatingAmount,uint256 treasurySharesMinted,uint256 lockedSharesMinted)",
  "event AllowanceClaimed(address indexed token,uint256 amountClaimed,uint256 sharesBurned)",
  "event TreasuryWithdrawn(address indexed token,uint256 amountWithdrawn,uint256 sharesBurned)",
  "event SettingsUpdated(uint256 operatingPct,uint256 treasuryPct,uint256 lockedPct,uint256 allowanceAmount,uint256 allowancePeriod)",
  "event SavePctUpdated(uint256 newSavePct)",
  "event PaymentSentAndSaved(address indexed token,address indexed recipient,uint256 amountSent,uint256 amountSaved,uint256 sharesMinted)",
  "event SavingsWithdrawn(address indexed token,uint256 amountWithdrawn,uint256 sharesBurned)",
  "event OwnershipTransferStarted(address indexed previousOwner,address indexed newOwner)",
  "event OwnershipTransferred(address indexed previousOwner,address indexed newOwner)",
  "event EmergencyWithdraw(address indexed token,uint256 amount)",
] as const;

export const socialJackpotAbi = [
  "function PLATFORM_FEE_BPS() view returns (uint256)",
  "function nextRoomId() view returns (uint256)",
  "function feeRecipient() view returns (address)",
  "function rooms(uint256) view returns (uint256 id,address creator,address token,uint256 entryFee,uint256 maxParticipants,uint256 numWinners,uint8 state,uint256 totalVotesCast)",
  "function roomParticipants(uint256,uint256) view returns (address)",
  "function participants(uint256,address) view returns (address addr,string pitch,uint256 votesReceived,bool hasVoted,bool exists)",
  "function createRoom(address _token,uint256 _entryFee,uint256 _maxParticipants,uint256 _numWinners) returns (uint256)",
  "function enterRoom(uint256 roomId,string pitch)",
  "function vote(uint256 roomId,address candidate)",
  "function getParticipantInfo(uint256 roomId,address user) view returns (string pitch,uint256 votesReceived,bool hasVoted)",
  "event RoomCreated(uint256 indexed roomId,address indexed creator,address token,uint256 entryFee,uint256 maxParticipants,uint256 numWinners)",
  "event UserEntered(uint256 indexed roomId,address indexed user,string pitch)",
  "event VotingStarted(uint256 indexed roomId)",
  "event Voted(uint256 indexed roomId,address indexed voter,address indexed candidate)",
  "event RoomResolved(uint256 indexed roomId,address[] winners,uint256 payoutPerWinner)",
  "event PlatformFeePaid(uint256 indexed roomId,address indexed recipient,uint256 amount)",
] as const;

export const erc20Abi = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
  "function balanceOf(address) view returns (uint256)",
  "function allowance(address owner,address spender) view returns (uint256)",
  "function approve(address spender,uint256 value) returns (bool)",
  "function transfer(address to,uint256 value) returns (bool)",
  "function transferFrom(address from,address to,uint256 value) returns (bool)",
  "event Approval(address indexed owner,address indexed spender,uint256 value)",
  "event Transfer(address indexed from,address indexed to,uint256 value)",
] as const;

export const erc4626Abi = [
  ...erc20Abi,
  "function asset() view returns (address)",
  "function totalAssets() view returns (uint256)",
  "function convertToShares(uint256 assets) view returns (uint256)",
  "function convertToAssets(uint256 shares) view returns (uint256)",
  "function maxDeposit(address receiver) view returns (uint256)",
  "function previewDeposit(uint256 assets) view returns (uint256)",
  "function deposit(uint256 assets,address receiver) returns (uint256)",
  "function maxMint(address receiver) view returns (uint256)",
  "function previewMint(uint256 shares) view returns (uint256)",
  "function mint(uint256 shares,address receiver) returns (uint256)",
  "function maxWithdraw(address owner) view returns (uint256)",
  "function previewWithdraw(uint256 assets) view returns (uint256)",
  "function withdraw(uint256 assets,address receiver,address owner) returns (uint256)",
  "function maxRedeem(address owner) view returns (uint256)",
  "function previewRedeem(uint256 shares) view returns (uint256)",
  "function redeem(uint256 shares,address receiver,address owner) returns (uint256)",
  "event Deposit(address indexed sender,address indexed owner,uint256 assets,uint256 shares)",
  "event Withdraw(address indexed sender,address indexed receiver,address indexed owner,uint256 assets,uint256 shares)",
] as const;

