/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ISmartRouter, ISmartRouterInterface } from "../../RouterFactory.sol/ISmartRouter.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_owner",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_factory",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "_operatingPct",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_treasuryPct",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_lockedPct",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_allowanceAmount",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_allowancePeriod",
        "type": "uint256"
      }
    ],
    "name": "initialize",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class ISmartRouter__factory {
    static readonly abi = _abi;
    static createInterface(): ISmartRouterInterface {
      return new Interface(_abi) as ISmartRouterInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ISmartRouter {
      return new Contract(address, _abi, runner) as unknown as ISmartRouter;
    }
  }
  