/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IRouterFactory, IRouterFactoryInterface } from "../../SmartRouter.sol/IRouterFactory.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      }
    ],
    "name": "getVault",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IRouterFactory__factory {
    static readonly abi = _abi;
    static createInterface(): IRouterFactoryInterface {
      return new Interface(_abi) as IRouterFactoryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IRouterFactory {
      return new Contract(address, _abi, runner) as unknown as IRouterFactory;
    }
  }
  