/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRouterFactory } from './IRouterFactory.js';
export type { SmartRouter } from './SmartRouter.js';