/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface SmartRouterInterface extends Interface {
    getFunction(nameOrSignature: "acceptOwnership" | "allowanceAmount" | "allowancePeriod" | "claimAllowance" | "emergencyWithdraw" | "factory" | "getLockedValue" | "getSavingsValue" | "getTreasuryValue" | "initialize" | "lastAllowanceRelease" | "lockedPct" | "lockedShares" | "operatingPct" | "owner" | "payAndSave" | "pendingOwner" | "processPayment" | "savePct" | "savedPrincipal" | "savedShares" | "transferOwnership" | "treasuryPct" | "treasuryShares" | "updateSavePct" | "updateSettings" | "withdrawSavings" | "withdrawTreasury"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AllowanceClaimed" | "EmergencyWithdraw" | "Initialized" | "OwnershipTransferStarted" | "OwnershipTransferred" | "PaymentProcessed" | "PaymentSentAndSaved" | "SavePctUpdated" | "SavingsWithdrawn" | "SettingsUpdated" | "TreasuryWithdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'acceptOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'allowanceAmount', values?: undefined): string;
encodeFunctionData(functionFragment: 'allowancePeriod', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimAllowance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'emergencyWithdraw', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'factory', values?: undefined): string;
encodeFunctionData(functionFragment: 'getLockedValue', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getSavingsValue', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTreasuryValue', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'lastAllowanceRelease', values?: undefined): string;
encodeFunctionData(functionFragment: 'lockedPct', values?: undefined): string;
encodeFunctionData(functionFragment: 'lockedShares', values?: undefined): string;
encodeFunctionData(functionFragment: 'operatingPct', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'payAndSave', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'pendingOwner', values?: undefined): string;
encodeFunctionData(functionFragment: 'processPayment', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'savePct', values?: undefined): string;
encodeFunctionData(functionFragment: 'savedPrincipal', values?: undefined): string;
encodeFunctionData(functionFragment: 'savedShares', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'treasuryPct', values?: undefined): string;
encodeFunctionData(functionFragment: 'treasuryShares', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateSavePct', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateSettings', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawSavings', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdrawTreasury', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'acceptOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowanceAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowancePeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimAllowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'factory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLockedValue', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSavingsValue', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTreasuryValue', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastAllowanceRelease', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockedPct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockedShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'operatingPct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'payAndSave', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'processPayment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'savePct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'savedPrincipal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'savedShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasuryPct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasuryShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateSavePct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateSettings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawSavings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawTreasury', data: BytesLike): Result;
  }

  
    export namespace AllowanceClaimedEvent {
      export type InputTuple = [token: AddressLike, amountClaimed: BigNumberish, sharesBurned: BigNumberish];
      export type OutputTuple = [token: string, amountClaimed: bigint, sharesBurned: bigint];
      export interface OutputObject {token: string, amountClaimed: bigint, sharesBurned: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EmergencyWithdrawEvent {
      export type InputTuple = [token: AddressLike, amount: BigNumberish];
      export type OutputTuple = [token: string, amount: bigint];
      export interface OutputObject {token: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferStartedEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PaymentProcessedEvent {
      export type InputTuple = [token: AddressLike, totalAmount: BigNumberish, operatingAmount: BigNumberish, treasurySharesMinted: BigNumberish, lockedSharesMinted: BigNumberish];
      export type OutputTuple = [token: string, totalAmount: bigint, operatingAmount: bigint, treasurySharesMinted: bigint, lockedSharesMinted: bigint];
      export interface OutputObject {token: string, totalAmount: bigint, operatingAmount: bigint, treasurySharesMinted: bigint, lockedSharesMinted: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PaymentSentAndSavedEvent {
      export type InputTuple = [token: AddressLike, recipient: AddressLike, amountSent: BigNumberish, amountSaved: BigNumberish, sharesMinted: BigNumberish];
      export type OutputTuple = [token: string, recipient: string, amountSent: bigint, amountSaved: bigint, sharesMinted: bigint];
      export interface OutputObject {token: string, recipient: string, amountSent: bigint, amountSaved: bigint, sharesMinted: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SavePctUpdatedEvent {
      export type InputTuple = [newSavePct: BigNumberish];
      export type OutputTuple = [newSavePct: bigint];
      export interface OutputObject {newSavePct: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SavingsWithdrawnEvent {
      export type InputTuple = [token: AddressLike, amountWithdrawn: BigNumberish, sharesBurned: BigNumberish];
      export type OutputTuple = [token: string, amountWithdrawn: bigint, sharesBurned: bigint];
      export interface OutputObject {token: string, amountWithdrawn: bigint, sharesBurned: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SettingsUpdatedEvent {
      export type InputTuple = [operatingPct: BigNumberish, treasuryPct: BigNumberish, lockedPct: BigNumberish, allowanceAmount: BigNumberish, allowancePeriod: BigNumberish];
      export type OutputTuple = [operatingPct: bigint, treasuryPct: bigint, lockedPct: bigint, allowanceAmount: bigint, allowancePeriod: bigint];
      export interface OutputObject {operatingPct: bigint, treasuryPct: bigint, lockedPct: bigint, allowanceAmount: bigint, allowancePeriod: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TreasuryWithdrawnEvent {
      export type InputTuple = [token: AddressLike, amountWithdrawn: BigNumberish, sharesBurned: BigNumberish];
      export type OutputTuple = [token: string, amountWithdrawn: bigint, sharesBurned: bigint];
      export interface OutputObject {token: string, amountWithdrawn: bigint, sharesBurned: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SmartRouter extends BaseContract {
    
    connect(runner?: ContractRunner | null): SmartRouter;
    waitForDeployment(): Promise<this>;

    interface: SmartRouterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    acceptOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    allowanceAmount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    allowancePeriod: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    claimAllowance: TypedContractMethod<
      [token: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    emergencyWithdraw: TypedContractMethod<
      [token: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    factory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getLockedValue: TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getSavingsValue: TypedContractMethod<
      [token: AddressLike, ],
      [[bigint, bigint, bigint] & {principal: bigint, totalValue: bigint, yieldEarned: bigint }],
      'view'
    >
    

    
    getTreasuryValue: TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [_owner: AddressLike, _factory: AddressLike, _operatingPct: BigNumberish, _treasuryPct: BigNumberish, _lockedPct: BigNumberish, _allowanceAmount: BigNumberish, _allowancePeriod: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    lastAllowanceRelease: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    lockedPct: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    lockedShares: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    operatingPct: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    payAndSave: TypedContractMethod<
      [token: AddressLike, recipient: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    pendingOwner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    processPayment: TypedContractMethod<
      [token: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    savePct: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    savedPrincipal: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    savedShares: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    treasuryPct: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    treasuryShares: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    updateSavePct: TypedContractMethod<
      [_savePct: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateSettings: TypedContractMethod<
      [_operatingPct: BigNumberish, _treasuryPct: BigNumberish, _lockedPct: BigNumberish, _allowanceAmount: BigNumberish, _allowancePeriod: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawSavings: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    withdrawTreasury: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'acceptOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'allowanceAmount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'allowancePeriod'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'claimAllowance'): TypedContractMethod<
      [token: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'emergencyWithdraw'): TypedContractMethod<
      [token: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'factory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getLockedValue'): TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getSavingsValue'): TypedContractMethod<
      [token: AddressLike, ],
      [[bigint, bigint, bigint] & {principal: bigint, totalValue: bigint, yieldEarned: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getTreasuryValue'): TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [_owner: AddressLike, _factory: AddressLike, _operatingPct: BigNumberish, _treasuryPct: BigNumberish, _lockedPct: BigNumberish, _allowanceAmount: BigNumberish, _allowancePeriod: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'lastAllowanceRelease'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lockedPct'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lockedShares'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'operatingPct'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'payAndSave'): TypedContractMethod<
      [token: AddressLike, recipient: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'pendingOwner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'processPayment'): TypedContractMethod<
      [token: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'savePct'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'savedPrincipal'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'savedShares'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'treasuryPct'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'treasuryShares'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'updateSavePct'): TypedContractMethod<
      [_savePct: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateSettings'): TypedContractMethod<
      [_operatingPct: BigNumberish, _treasuryPct: BigNumberish, _lockedPct: BigNumberish, _allowanceAmount: BigNumberish, _allowancePeriod: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawSavings'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawTreasury'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AllowanceClaimed'): TypedContractEvent<AllowanceClaimedEvent.InputTuple, AllowanceClaimedEvent.OutputTuple, AllowanceClaimedEvent.OutputObject>;
getEvent(key: 'EmergencyWithdraw'): TypedContractEvent<EmergencyWithdrawEvent.InputTuple, EmergencyWithdrawEvent.OutputTuple, EmergencyWithdrawEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferStarted'): TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PaymentProcessed'): TypedContractEvent<PaymentProcessedEvent.InputTuple, PaymentProcessedEvent.OutputTuple, PaymentProcessedEvent.OutputObject>;
getEvent(key: 'PaymentSentAndSaved'): TypedContractEvent<PaymentSentAndSavedEvent.InputTuple, PaymentSentAndSavedEvent.OutputTuple, PaymentSentAndSavedEvent.OutputObject>;
getEvent(key: 'SavePctUpdated'): TypedContractEvent<SavePctUpdatedEvent.InputTuple, SavePctUpdatedEvent.OutputTuple, SavePctUpdatedEvent.OutputObject>;
getEvent(key: 'SavingsWithdrawn'): TypedContractEvent<SavingsWithdrawnEvent.InputTuple, SavingsWithdrawnEvent.OutputTuple, SavingsWithdrawnEvent.OutputObject>;
getEvent(key: 'SettingsUpdated'): TypedContractEvent<SettingsUpdatedEvent.InputTuple, SettingsUpdatedEvent.OutputTuple, SettingsUpdatedEvent.OutputObject>;
getEvent(key: 'TreasuryWithdrawn'): TypedContractEvent<TreasuryWithdrawnEvent.InputTuple, TreasuryWithdrawnEvent.OutputTuple, TreasuryWithdrawnEvent.OutputObject>;

    filters: {
      
      'AllowanceClaimed(address,uint256,uint256)': TypedContractEvent<AllowanceClaimedEvent.InputTuple, AllowanceClaimedEvent.OutputTuple, AllowanceClaimedEvent.OutputObject>;
      AllowanceClaimed: TypedContractEvent<AllowanceClaimedEvent.InputTuple, AllowanceClaimedEvent.OutputTuple, AllowanceClaimedEvent.OutputObject>;
    

      'EmergencyWithdraw(address,uint256)': TypedContractEvent<EmergencyWithdrawEvent.InputTuple, EmergencyWithdrawEvent.OutputTuple, EmergencyWithdrawEvent.OutputObject>;
      EmergencyWithdraw: TypedContractEvent<EmergencyWithdrawEvent.InputTuple, EmergencyWithdrawEvent.OutputTuple, EmergencyWithdrawEvent.OutputObject>;
    

      'Initialized(uint64)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'OwnershipTransferStarted(address,address)': TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
      OwnershipTransferStarted: TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PaymentProcessed(address,uint256,uint256,uint256,uint256)': TypedContractEvent<PaymentProcessedEvent.InputTuple, PaymentProcessedEvent.OutputTuple, PaymentProcessedEvent.OutputObject>;
      PaymentProcessed: TypedContractEvent<PaymentProcessedEvent.InputTuple, PaymentProcessedEvent.OutputTuple, PaymentProcessedEvent.OutputObject>;
    

      'PaymentSentAndSaved(address,address,uint256,uint256,uint256)': TypedContractEvent<PaymentSentAndSavedEvent.InputTuple, PaymentSentAndSavedEvent.OutputTuple, PaymentSentAndSavedEvent.OutputObject>;
      PaymentSentAndSaved: TypedContractEvent<PaymentSentAndSavedEvent.InputTuple, PaymentSentAndSavedEvent.OutputTuple, PaymentSentAndSavedEvent.OutputObject>;
    

      'SavePctUpdated(uint256)': TypedContractEvent<SavePctUpdatedEvent.InputTuple, SavePctUpdatedEvent.OutputTuple, SavePctUpdatedEvent.OutputObject>;
      SavePctUpdated: TypedContractEvent<SavePctUpdatedEvent.InputTuple, SavePctUpdatedEvent.OutputTuple, SavePctUpdatedEvent.OutputObject>;
    

      'SavingsWithdrawn(address,uint256,uint256)': TypedContractEvent<SavingsWithdrawnEvent.InputTuple, SavingsWithdrawnEvent.OutputTuple, SavingsWithdrawnEvent.OutputObject>;
      SavingsWithdrawn: TypedContractEvent<SavingsWithdrawnEvent.InputTuple, SavingsWithdrawnEvent.OutputTuple, SavingsWithdrawnEvent.OutputObject>;
    

      'SettingsUpdated(uint256,uint256,uint256,uint256,uint256)': TypedContractEvent<SettingsUpdatedEvent.InputTuple, SettingsUpdatedEvent.OutputTuple, SettingsUpdatedEvent.OutputObject>;
      SettingsUpdated: TypedContractEvent<SettingsUpdatedEvent.InputTuple, SettingsUpdatedEvent.OutputTuple, SettingsUpdatedEvent.OutputObject>;
    

      'TreasuryWithdrawn(address,uint256,uint256)': TypedContractEvent<TreasuryWithdrawnEvent.InputTuple, TreasuryWithdrawnEvent.OutputTuple, TreasuryWithdrawnEvent.OutputObject>;
      TreasuryWithdrawn: TypedContractEvent<TreasuryWithdrawnEvent.InputTuple, TreasuryWithdrawnEvent.OutputTuple, TreasuryWithdrawnEvent.OutputObject>;
    
    };
  }