/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { Dummy, DummyInterface } from "../../mocks/Dummy.js";

  const _abi = [
  {
    "inputs": [],
    "name": "token",
    "outputs": [
      {
        "internalType": "contract IERC20",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b50608d80601a5f395ff3fe6080604052348015600e575f5ffd5b50600436106026575f3560e01c8063fc0c546a14602a575b5f5ffd5b5f54603b906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f3fea264697066735822122098647617ed78ceffc6b1e6731a84b852862e6b48b4838a493e57f7caa5d0cdcf64736f6c63430008230033";

  
      type DummyConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: DummyConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class Dummy__factory extends ContractFactory {
    
      constructor(...args: DummyConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<Dummy & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): Dummy__factory {
      return super.connect(runner) as Dummy__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): DummyInterface {
      return new Interface(_abi) as DummyInterface;
    }
    
    override attach(address: string | Addressable): Dummy {
      return super.attach(address) as Dummy;
    }
  static connect(address: string, runner?: ContractRunner | null): Dummy {
      return new Contract(address, _abi, runner) as unknown as Dummy;
    }
  }

  
  